server:
  port: 8080

spring:
 application:
      name: LoginRegistrationDemo

 datasource:
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://localhost:5432/DemoRegistration
   username: postgres
   password: 16260

 jpa:
   hibernate:
     ddl-auto: create
   properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
     show-sql: true




